### ISSUE TITLE
On web version 2.0.2 works in Dartium but breaks after dart2js compilation

### ISSUE THREAD

**Issue by vadimtsushko** [dart-lang/resource#16]
On SDK:  Dart VM version: 1.20.1 (Wed Oct 12 15:07:45 2016) on "windows_x64" and current package version (2.0.2) sample code work in Dartium but break after dart2js compilation in Chrome with cryptic stacktrace

```
EXCEPTION: Unsupported operation: Platform._version
EXCEPTION: Unsupported operation: Platform._version
STACKTRACE:
Unsupported operation: Platform._version
    at wrapException (http://localhost:63342/bad_resource/web/main.dart.js:3707:17)
    at _Platform__version (http://localhost:63342/bad_resource/web/main.dart.js:17427:15)
    at _Platform_version (http://localhost:63342/bad_resource/web/main.dart.js:17436:16)
    at http://localhost:63342/bad_resource/web/main.dart.js:30585:14
    at Isolate.prototype.(anonymous function) (http://localhost:63342/bad_resource/web/main.dart.js:30698:42)
    at _getHttpVersion (http://localhost:63342/bad_resource/web/main.dart.js:17417:23)
    at http://localhost:63342/bad_resource/web/main.dart.js:28907:256
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:63342/bad_resource/web/main.dart.js:6282:15)
    at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$2 (http://localhost:63342/bad_resource/web/main.dart.js:6729:14)
    at _awaitOnObject_closure.dart._awaitOnObject_closure.call$1 (http://localhost:63342/bad_resource/web/main.dart.js:6717:34)
```

I've uploaded sample project which reproduce that behavior https://github.com/vadimtsushko/bad_resource

**Comment by lrhn** [comment]
@sigmundch @nex3 
This seems like a dart2js issue (the Platform._version doesn't come from the resource package).
After trying to debug this, it seems that the compilation chooses the dart.io branch of:
```dart
import "io_none.dart"
    if (dart.library.io) "io_io.dart"
    if (dart.library.html) "io_html.dart"
    as io;
```
That is either a bug in dart2js or `pub server` not invoking dart2js correctly (but I'm doubting the latter).

I can "solve" this by swapping the conditions and testing html first, but it *is* a bug for dart2js to compile a web application and have dart.library.io as true.

**Comment by sigmundch** [comment]
The issue is that `pub` is providing a different path to SDK files than what dart2js expects.

The way we derive whether a library is supported or not is encoded in the URI to resolve the library. We should change this long term and be more direct about it in our API. (since it's not an obvious convention for tools that invoke dart2js as a library).

In this case what happens is that on the command line the `dart:io` location is resolved as `unsupported:`, but on pub it's resolved to: `file:///path/to/your/package/web/packages/$sdk/lib/io/io.dart`.

I can imagine 2 fixes in pub:
 - match what we have in `dart_client.platform` for `dart:io`. Today that is `unsupported:` but in the future it might need to be `unsupported:///path/to/your/package/web/packages/$sdk/lib/io/io.dart`, or
 - extend the defined environment to include {'dart.library.io' : 'false'} (pub already provides an environment, it would just mean to add an extra key-value pair)

On the dart2js side, we can make these environment values part of the *.platform files and not use the `unsupported:` scheme for this purpose.

/cc @munificent

**Comment by lrhn** [comment]
Dartium no longer exists.
